### ISSUE TITLE
Build error: 'OID' has not been declared

### ISSUE THREAD

**Issue by dleach02** [openweave/openweave-nrf52840-lock-example#15]
Trying build this example to get some insight on openweave but I get the following error:

../../src/include/Weave/Support/ASN1.h:123:28: error: 'OID' has not been declared
     ASN1_ERROR GetObjectId(OID& oid);

This is a virgin Ubuntu setup following the instructions of setup and build from this example. Any help would be appreciated.

**Comment by jaylogue** [comment]
Hi David,

I was able to reproduce your problem on a vanilla Ubuntu 18 system.  As I suspect you already discovered, building OpenWeave relies on an installation of the 'python' command (i.e. python 2.7) which is not installed by default in later Ubuntu releases.  This should have been called out as a dependency in our instructions.

The error you gave occurs after having attempted to build without python 2.7 installed, and then subsequently installing python and trying again.  Unfortunately, at this point the source tree is in a bad state and the compilation fails with the "'OID' has not been declared" error.

We will fix this problem.  In the meantime, you should be able to recover by re-initializing the openweave-core submodule as follows:

```
git submodule deinit -f third_party/openweave-core
git submodule update --init
```

As the problem exists is in OpenWeave itself, I will open an new issue in that repo.

**Comment by jaylogue** [comment]
I've opened [issue 238](https://github.com/openweave/openweave-core/issues/238) in openweave-core for this.

**Comment by jaylogue** [comment]
The root issue in openweave-core that caused this problem has been fixed.
