### ISSUE TITLE
Next Steps?

### ISSUE THREAD

**Issue by Dayna-A** [openweave/openweave-nrf52840-lock-example#30]
Hello, 
Are you able to point me to the next steps for provisioning a network with 3 of these devices?
Thank you!

**Comment by turon** [comment]
Hi @Dayna-A,

The best way to get started with provisioning Weave nodes is over BLE using `weave-device-mgr`.

BUILD:
```
# From top level of openweave-nrf52840-lock-example
cd third_party/openweave-core
make -f Makefile-Standalone
```

RUN:
```
# First time setup:
pip install pycryptodomex
# From top level of openweave-core
./output/x86_64-unknown-linux-gnu/bin/weave-device-mgr 
```

NETWORK PROVISION:
```
# From top level of openweave-core
# Use nRFConnect with RSSI filter to find device
> ble-scan -t30
> ble-scan-connect NEST-0022
> connect -b -p NESTUS
> add-thread-network "OpenThread" dead00beef00cafe 00112233445566778899aabbccddeeff pan-id=1 thread-channel=11
> enable-network 1
```
This will network provision the lock with the Thread credentials specified in the `add-thread-network` command.  You can then use the `ot-cli` app from the OpenThread project to create a router device for the lock to connect to:

```
minicomm -D /dev/ttyACM0
> panid 1
> ifconfig up
> thread start
> state
leader
> child table
# ... if you see a child, that is the lock attached ...
```

These instructions just cover the network provisioning portion.  To have a complete setup, fabric provisioning and service provisioning are also required.  This can also be done with weave-device-mgr.  More details on weave-device-mgr can be found here: https://openweave.io/guides/tools/device-manager.
