### ISSUE TITLE
Thread configuration adjustments to increase reliability in less than ideal RF environments

### ISSUE THREAD

**Issue by pierredelisle7** [openweave/openweave-nrf52840-lock-example#39]
When operating in a less than ideal RF environment, having a more forgiving configuration makes  thread a great deal more reliable.
  
We'd like to suggest small alterations to the OpenThread configurations:
 
In main/include/OpenThreadConfig.h:

#define OPENTHREAD_CONFIG_MAC_MAX_FRAME_RETRIES_DIRECT 15
#define OPENTHREAD_CONFIG_MAC_MAX_FRAME_RETRIES_INDIRECT 1
#define OPENTHREAD_CONFIG_MAC_MAX_TX_ATTEMPTS_INDIRECT_POLLS 16

Also, it would be good to add the following to make it obvious for developers how to increase the verbosity level of Thread whenever necessary:

// Uncomment the statement below to get more verbose output from Thread. Useful if experiencing
// issues with Thread.
// #define OPENTHREAD_CONFIG_LOG_LEVEL OT_LOG_LEVEL_INFO

**Comment by jaylogue** [comment]
Fixed in openweave-nrf52840-lock-example:master in change 31a62de3.
