### ISSUE TITLE
Using USB CDC ACM for data logging with this example

### ISSUE THREAD

**Issue by jdinh1** [openweave/openweave-nrf52840-lock-example#49]
Hello OpenWeave team,

This is not an issue but rather a request for help and addition information. 
I want to implement the USB CDC ACM class from nRF SDK to this example and use it for data logging/exchange purposes. What I've done so far was:

1. Added the required usbd libraries to the Makefile
```
SRCS = \ 
....
    $(NRF5_SDK_ROOT)/components/libraries/usbd/app_usbd.c \
    $(NRF5_SDK_ROOT)/components/libraries/usbd/class/cdc/acm/app_usbd_cdc_acm.c \
    $(NRF5_SDK_ROOT)/components/libraries/usbd/app_usbd_core.c \
    $(NRF5_SDK_ROOT)/components/libraries/usbd/app_usbd_serial_num.c \
    $(NRF5_SDK_ROOT)/components/libraries/usbd/app_usbd_string_desc.c \
....
INC_DIRS = \
....
    $(NRF5_SDK_ROOT)/components/libraries/usbd/class/cdc \
    $(NRF5_SDK_ROOT)/components/libraries/usbd \
    $(NRF5_SDK_ROOT)/components/libraries/usbd/class/cdc/acm \
....
```

2. Port over USB initialization code from nRF SDK's USB_CDC_ACM's example to `main.cpp`
```
....
APP_USBD_CDC_ACM_GLOBAL_DEF(m_app_cdc_acm,
                            cdc_acm_user_ev_handler,
                            CDC_ACM_COMM_INTERFACE,
                            CDC_ACM_DATA_INTERFACE,
                            CDC_ACM_COMM_EPIN,
                            CDC_ACM_DATA_EPIN,
                            CDC_ACM_DATA_EPOUT,
                            APP_USBD_CDC_COMM_PROTOCOL_AT_V250
);
....
```

Compiling this will give many errors as the usbd library uses a lot of designated initializers, which are not supported in C++.

Before I get further down the rabbit's hole trying to go around this issue, I was wondering if this is the correct approach to implementing USB CDC ACM to this example? Or is there exist an easier way to do so?

Thanks,
Jonathan

**Comment by jaylogue** [comment]
Hi Jonathan,

This is probably a better question for the [Nordic DevZone forum](https://devzone.nordicsemi.com/). 
However, taking a quick look at the header files (app_usbd_cdc_acm.h and app_usbd_cdc_acm_internal.h), it's clear that they intended them to be used from C++, hence the extern "C" wrappers.  Perhaps they're expecting the code to be compiled with a later version of C++?

A quick work-around would be to move the initialization of the global CDC_ACM class instance into a .c file and then reference the instance as extern "C" in main.cpp.

**Comment by jdinh1** [comment]
Hi Jay,

Thank you for your suggestion, I will definitely give it a try on this weekend.

Jonathan
